version: '3.9'

networks:
  snyk:
    driver: bridge

services:
  snyk_backend:
    hostname: snyk_backend
    image: snyk/snyk:alpine
    container_name: snyk-backend
    command: ["snyk", "code", "test", "/project/backend/"]
    volumes:
      - ./backend/:/project/backend/
    networks:
      - snyk
    env_file:
      - .env
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN}

  snyk_frontend:
    hostname: snyk_frontend
    image: snyk/snyk:alpine
    command: ["snyk", "code", "test", "/project/frontend/"]
    container_name: snyk-frontend
    volumes:
      - ./frontend/:/project/frontend/
    networks:
      - snyk
    env_file:
      - .env
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN}
  