#!/bin/sh

apt-get update && apt-get upgrade -y && apt install python3 -y
chmod -R 777 /project/
npm install @angular-eslint/builder --save --legacy-peer-deps
npm install --save-dev
npm run lint
npm run format
exec ${@}
